image: paciolanhub/alpine-node-dev:10.15.3c

variables:
  REPO_URL: gitlabdev.paciolan.info
  GITHUB_URL: https://github.com/Paciolan/express-easy-routes

stages:
  - build
  - deploy

Build & Test:
  stage: build
  image: paciolanhub/alpine-node-dev:10.15.3c
  tags:
    - gitlabdev
  except:
    - tags
  before_script:
    - npm ci
  script:
    - npm run lint
    - npm run test:coverage -- --colors
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/

Deploy:
  stage: deploy
  environment: NPM
  tags:
    - gitlabdev
  only:
    - master
  except:
    - tags
  before_script:
    # add git ssh key
    - ssh-keyscan $SSH_KNOWN_HOSTS >> ~/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - echo "$GIT_SSH_PRIV_KEY" | ssh-add -
  script:
    # publish
    - semantic-release-gitlab

    # set repository to github for npm link
    - node -e "require('fs').writeFileSync('./package.json', JSON.stringify(Object.assign(require('./package.json'), {repository:{type:'git',url:'$GITHUB_URL'}}), null, 2), 'utf8')"

    - npm-publish-git-tag --access public

    # debug
    - echo published to https://www.npmjs.com/package/$(node -p "require('./package.json').name")
